Revert "Extract native libs from jline (#13345)" (#13359)
I have accidentally introduced too many cache problems in #13345 which leads to broken local builds as well as on CI (for example at https://github.com/enso-org/enso/actions/runs/15851909740/job/44688391534?pr=13356#step:15:1050). Local build is broken when one tries to `buildEngineDistribution`, then modifies some `*.enso` source, and then `buildEngineDistribution` again. This leads to
```
java.lang.module.FindException: Two versions of module org.jline.nativ found in /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/../component (jline-native-3.26.3.jar and jline-native-3.26.3-thin.jar)
```

# Important Notes
Reverting this ASAP to unblock other PRs. I will reintroduce this PR after I have extensively tested the caching mechanisms.