Engine Nightly Checks fixes (#13781)
* Partial fixes to nightly tests

An attempt to fix remaining failures in our extra tests running nightly.

* Stop skipping on failure

Will probably start failing on CI, as it should to begin with.

* Partial revert of #11805

PR #11805 removed support for storing `0.0.0-dev` versions. Sadly it
went unnoticed that it broke our test-suite. Bringing it back,
optionally, so that we can keep using it in our tests.

* nit

* Stabilize Table_Visualization tests

If data quality metrics are still pending for distinct count, it would
return `Nothing`. This in turn meant that our tests in `Table_Spec`
could be flaky as `is_using_multi_filter` would return `False` in that
case. This was more visible in our native image builds as things were
faster.
Not sure why the behaviour was changed in #13583.

* Fix module path for editions

If the edition was missing users would get messages along the line of
```
ava.lang.IllegalAccessError: class org.enso.editions.updater.EditionUpdater (in module org.enso.editions.updater) cannot access class org.enso.downloader.http.URIBuilder (in module org.enso.downloader) because module org.enso.editions.updater does not read module org.enso.downloader
	at org.enso.editions.updater/org.enso.editions.updater.EditionUpdater.$anonfun$fetchManifests$2(EditionUpdater.scala:100)
```
which is bad.

* Add missing test

* Remove spurious asserts

`assertSameElements` that follows already checks the size of the
responses **and** provides a more useful error - the messages that have
been received. Without the latter, there is little one can do to debug
the issue on CI.