Fix dependencies on `library-manager` (#12419)
* Fix deps on `library-manager`

Only tests should depend on logging setup, for test purposes.
Fixes ClassNotFoundException:
```
[info] LibraryDownloadTest:
[info] DownloadingLibraryCache
SLF4J(I): Attempting to load provider "org.enso.logging.service.logback.test.provider.TestLogProvider" specified via "slf4j.provider" system propertyTests 0s
SLF4J(E): Failed to instantiate the specified SLF4JServiceProvider (org.enso.logging.service.logback.test.provider.TestLogProvider)
SLF4J(E): Reported exception:
java.lang.ClassNotFoundException: org.enso.logging.service.logback.test.provider.TestLogProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.slf4j.LoggerFactory.loadExplicitlySpecified(LoggerFactory.java:226)
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:122)
```

* Drop `library-manager-test`

Replaced by setting dependencies between projects appropriately using
classifiers.