Meta.meta on synhetic module throws dataflow error (#13110)
It appears that under some undetermined scenarios synthetic modules didn't have an IR. Therefore calling any methods on them would lead to NPE.
Encountered the crash in the wild:
```
[org.enso.interpreter.instrument.job.ProgramExecutionSupport$] Execution of function main failed (Cannot invoke "org.enso.compiler.core.ir.Module.isPrivate()" because "this.ir" is null).
java.lang.NullPointerException: Cannot invoke "org.enso.compiler.core.ir.Module.isPrivate()" because "this.ir" is null
at org.enso.runtime/org.enso.interpreter.runtime.Module.isPrivate(Module.java:248)
at org.enso.runtime/org.enso.interpreter.node.expression.builtin.meta.MetaKindNode.execute(MetaKindNode.java:34)
at org.enso.runtime/org.enso.interpreter.node.expression.builtin.meta.MetaKindMethodGen.handleExecute(MetaKindMethodGen.java:114)
at
```

This change enforces that synthetic modules are always private, irrespective of whether they have an IR or not.
This revealed some violations in our own stdlib which had to be workaround by creating stub modules.